"""initial_migration

Revision ID: 4293e7abed55
Revises: 
Create Date: 2026-04-28 08:09:06.825213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4293e7abed55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='shipmentstatus'), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('origin_city', sa.String(length=255), nullable=False),
    sa.Column('origin_code', sa.String(length=50), nullable=False),
    sa.Column('origin_coords', sa.JSON(), nullable=True),
    sa.Column('destination_city', sa.String(length=255), nullable=False),
    sa.Column('destination_code', sa.String(length=50), nullable=False),
    sa.Column('destination_coords', sa.JSON(), nullable=True),
    sa.Column('current_location', sa.JSON(), nullable=True),
    sa.Column('carrier', sa.String(length=255), nullable=False),
    sa.Column('cargo_type', sa.String(length=255), nullable=False),
    sa.Column('environmental_impact', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_tracking_number'), ['tracking_number'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'COMPANY_ADMIN', 'LOGISTICS_MANAGER', 'COMPLIANCE_OFFICER', 'SUSTAINABILITY_LEAD', 'STANDARD_DISPATCHER', 'DRIVER', name='userrole'), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('fleet_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('EV_SEMI', 'DIESEL_TRUCK', 'HYBRID_VAN', 'DRONE', name='vehicletype'), nullable=False),
    sa.Column('battery_health', sa.Float(), nullable=False),
    sa.Column('fuel_level', sa.Float(), nullable=False),
    sa.Column('last_maintenance', sa.Date(), nullable=True),
    sa.Column('current_driver_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'OUT_OF_SERVICE', name='fleetunitstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fleet_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleet_units_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_units_unit_id'), ['unit_id'], unique=True)

    op.create_table('shipment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'PICKED_UP', 'IN_TRANSIT', 'CUSTOMS_CLEARANCE', 'DELIVERED', 'DELAYED', 'ISSUE_REPORTED', name='shipmenteventtype'), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_events_shipment_id'), ['shipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_events_shipment_id'))

    op.drop_table('shipment_events')
    with op.batch_alter_table('fleet_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_units_unit_id'))
        batch_op.drop_index(batch_op.f('ix_fleet_units_organization_id'))

    op.drop_table('fleet_units')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_tracking_number'))
        batch_op.drop_index(batch_op.f('ix_shipments_organization_id'))

    op.drop_table('shipments')
    op.drop_table('organizations')
    # ### end Alembic commands ###
